### ISSUE TITLE
Feature request: Lock to horizontal/vertical while dragging

### ISSUE THREAD

**Issue by songcarver** [PavelLaptev/Figma-Warp#4]
Hello! Thanks for the excellent plugin.

I am hoping to move a point, but only on a single axis. Ie, to make a parallelogram. This might be achieved by shift-dragging a handle, or perhaps some other method.

**Comment by PavelLaptev** [comment]
@songcarver will check and add it to the next release. Thank you!

**Comment by PavelLaptev** [comment]
@songcarver done

**Comment by songcarver** [comment]
🕺Thanks!
